name: Elixir Type Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Run Dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: ["24.3.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-app: false

      # Don't cache PLTs based on mix.lock hash, as Dialyzer can incrementally update even old ones.
      # Cache key based on Elixir & Erlang version (also useful when running in matrix).
      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt_cache
        with:
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          path: priv/plts
      
      # Create PLTs if no cache was found.
      # (If they were cached at all, they'll be updated when we run mix dialyzer with no flags.)
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer
